import { getInstallationOctokit } from "../github/client.js";
import { fetchPRMetadata, fetchPRDiff, createDocPR } from "../github/pr.js";
import { readFile } from "../github/files.js";
import { runAnalyzerAgent } from "./analyzer.js";
import { runWriterAgent } from "./writer.js";
import type { JobPayload, PipelineResult, AgentRun, AnalysisResult, DocContent } from "../types/agents.js";

export async function runCoordinatorAgent(payload: JobPayload): Promise<PipelineResult> {
  const [owner, repo] = payload.repoFullName.split("/") as [string, string];
  const octokit = await getInstallationOctokit(payload.installationId);
  const agentRuns: AgentRun[] = [];

  // Coordinator phase 1: fetch PR data
  const coordStart = new Date().toISOString();
  const [prMetadata, diff] = await Promise.all([
    fetchPRMetadata(octokit, owner, repo, payload.prNumber),
    fetchPRDiff(octokit, owner, repo, payload.prNumber),
  ]);
  agentRuns.push({
    agent_name: "coordinator",
    started_at: coordStart,
    completed_at: new Date().toISOString(),
    input_summary: `PR #${payload.prNumber}`,
    output_summary: `Fetched PR #${payload.prNumber}: "${prMetadata.title}", ${diff.files.length} files changed`,
    status: "completed",
  });

  // Analyzer: understand what changed
  const analyzerStart = new Date().toISOString();
  const analysis = await runAnalyzerAgent(prMetadata, diff);
  agentRuns.push({
    agent_name: "analyzer",
    started_at: analyzerStart,
    completed_at: new Date().toISOString(),
    input_summary: `${diff.files.length} changed files`,
    output_summary: `Confidence: ${analysis.confidence_score.toFixed(2)} · ${analysis.public_interface_changes.length} interface changes`,
    status: "completed",
  });

  // Writer: generate documentation
  const writerStart = new Date().toISOString();
  const docContent = await runWriterAgent(prMetadata, analysis);
  agentRuns.push({
    agent_name: "writer",
    started_at: writerStart,
    completed_at: new Date().toISOString(),
    input_summary: `Analysis for PR #${payload.prNumber}`,
    output_summary: "Generated changelog entry + release notes",
    status: "completed",
  });

  // Coordinator phase 2: build and create Doc PR
  const [currentChangelog, currentReleaseNotes] = await Promise.all([
    readFile(octokit, owner, repo, "CHANGELOG.md"),
    readFile(octokit, owner, repo, "RELEASE_NOTES.md"),
  ]);

  const today = new Date().toISOString().split("T")[0]!;
  const newChangelog = prependSection(currentChangelog, `\n## [Unreleased] - ${today}\n\n${docContent.changelog_entry}\n`);
  const newReleaseNotes = prependSection(currentReleaseNotes, `\n## ${today} — PR #${payload.prNumber}\n\n${docContent.release_notes}\n`);

  const prBody = buildDocPRBody(payload.prNumber, prMetadata.title, analysis, docContent);
  const { number, html_url } = await createDocPR(
    octokit,
    owner,
    repo,
    payload.prNumber,
    [
      { path: "CHANGELOG.md", content: newChangelog },
      { path: "RELEASE_NOTES.md", content: newReleaseNotes },
    ],
    prBody
  );

  agentRuns[0]!.output_summary += ` → Doc PR #${number} created`;

  return { doc_pr_number: number, doc_pr_url: html_url, agent_runs: agentRuns };
}

function prependSection(existing: string, newSection: string): string {
  if (!existing) return `# Changelog\n${newSection}`;
  const lines = existing.split("\n");
  const insertAt = lines.findIndex((l) => l.startsWith("## "));
  if (insertAt === -1) return existing + newSection;
  lines.splice(insertAt, 0, ...newSection.split("\n"));
  return lines.join("\n");
}

function buildDocPRBody(sourcePrNumber: number, title: string, analysis: AnalysisResult, docContent: DocContent): string {
  return `## Documentation Update for PR #${sourcePrNumber}

**Source PR:** #${sourcePrNumber} — ${title}
**Confidence score:** ${analysis.confidence_score.toFixed(2)}

### Files Modified
- \`CHANGELOG.md\`
- \`RELEASE_NOTES.md\`

### Generated Changelog Entry
${docContent.changelog_entry}

### Generated Release Notes
${docContent.release_notes}

### Analysis Reasoning
${analysis.reasoning}

---
*Generated by DevLogAI using 3-agent Band SDK pipeline: Coordinator → Analyzer → Writer*`;
}
